ДЗ 2
NikitaA-12/2024-2-VK-EDU-Frontend-N-Abramov pull request #10
Opened 2024-10-05 14:35 UTC by NikitaA-12

# Домашнее задание № 2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:

1. Стилизовать форму отправки сообщений:
* Добавлен блок ввода текста с кнопкой отправки.
* Использованы стили для корректного отображения поля ввода и кнопки.
* Настроен размер поля ввода, добавлены отступы, цвета и другие визуальные элементы.

2. Сделать так, чтобы по нажатию на кнопку Enter сообщение сохранялось в localStorage и добавлялось к списку сообщений:
* Написан JavaScript-код, который отслеживает нажатие клавиши Enter.
* Реализована функция сохранения сообщения в localStorage с указанием текста и времени отправки.

3.  Сообщение сохраняется в виде объекта с полями text и time.
* Поле ввода очищается после нажатия на кнопку Enter:
* После отправки сообщения поле ввода очищается, возвращаясь к исходной высоте.
Добавлено сбросное действие для поля текста.
Сообщение должно содержать текст и время отправки:
В сообщение добавлено текущее время в формате "часы:минуты" при отправке.
Отображение сообщения включает текст и время, полученные при отправке.

2024-10-06 11:13 UTC, nelkor requested changes
При смене пользователя внешний вид сообщений должен меняться. Нужные сообщения должны становиться "твоими".

2024-10-06 11:13 UTC, nelkor commented on simple-chat/index.html
> +    <!-- Изменено на type="module" -->
Лишний комментарий. Там и так видно, что type module.

2024-10-06 11:13 UTC, nelkor commented on simple-chat/index.html
> +          <!-- Изменено на ./ для корректного отображения при сборке -->
Эти оба комментария тоже лишние.

2024-10-07 17:35 UTC, nelkor approved these changes

2024-10-07 19:53 UTC, merged

2024-10-07 19:54 UTC, martinkomitsky commented
10!