ДЗ 3
NikitaA-12/2024-2-VK-EDU-Frontend-N-Abramov pull request #11
Opened 2024-10-09 20:00 UTC by NikitaA-12

# Домашнее задание № 3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его. 

https://nikitaa-12.github.io/2024-2-VK-EDU-Frontend-N-Abramov/

Что было сделано:

1. Декомпозиция макета:
Разделение экрана на компоненты:
* Шапка: включает кнопку поиска, заголовок и кнопку "бургер".
* Чат: состоит из аватара, заголовка, последнего сообщения, времени и индикатора прочитанности/доставленности.
* "Парящая" кнопка: кнопка "создать чат". 

2. Структурирование кода:
* Код разделён на отдельные компоненты с созданием различных файлов для JavaScript и CSS.

3. Навигация:
* Предусмотрены переходы с экрана списка чатов на экран сообщений.
* Интегрирован существующий экран сообщений, разработанный в предыдущем домашнем задании, с новой страницей.

2024-10-11 10:50 UTC, nelkor requested changes
Если создать новый чат, его буква/цифра (аватарка) уезжает вверх.

В новый чат невозможно перейти.

При заходе в любой из первичных чатов видно одно и то же.

2024-10-21 07:02 UTC, nelkor requested changes
Вот таким способом можно сломать приложение. Подумай, как этого избежать.

![image](https://github.com/user-attachments/assets/36a0d35c-1b15-4e76-af35-41cfc59a1257)

2024-10-22 14:41 UTC, nelkor requested changes
Enter не отправляет сообщения.

Переключился на собеседника, но сообщения отправляются всё равно от своего лица.

2024-10-23 13:13 UTC, nelkor approved these changes

2024-10-23 16:52 UTC, martinkomitsky commented
12!

2024-10-23 16:52 UTC, merged