ДЗ 5
NikitaA-12/2024-2-VK-EDU-Frontend-N-Abramov pull request #13
Opened 2024-11-05 01:40 UTC by NikitaA-12

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:
1. Удаление старого способа подключения иконок и добавление нового:

* Устаревший метод подключения иконок был удален, и вместо этого была добавлена ссылка на библиотеку Material Icons, чтобы можно было использовать иконки в стиле Material Design. 

2. Переписывание компонентов на React:

* Все компоненты были переписаны в формате функциональных компонентов React. Это включало пересмотр подходов и перевод логики в React-компоненты, чтобы исключить прямую работу с DOM. Теперь все взаимодействия с элементами выполняются исключительно с помощью React-хуков и состояния. 

3. Восстановление стилей для всех компонентов:

* Стили, которые применялись ранее, были адаптированы и восстановлены для новых React-компонентов. Это гарантировало, что внешний вид и оформление остались прежними, несмотря на изменения в логике. 

4. Восстановление функциональности всех компонентов:

* Логика и поведение всех компонентов были перенесены в React и проверены для полного восстановления всех функций, включая обработку кликов, ввод текста и прочие пользовательские действия.

2024-11-07 07:58 UTC, nelkor requested changes
В целом, код выглядит неплохо, кое что надо поправить.

2024-11-07 07:58 UTC, nelkor commented on reactChat/index.html
> +    <title>Vite + React</title>
Заголовок страницы можно и заменить)

2024-11-07 07:58 UTC, nelkor commented on reactChat/src/App.jsx
> +import './styles/chat-item.css';
```suggestion
import './styles/index.scss';
```

Было бы лучше использовать один индексный файл для стилей, а в него уже импортировать остальные файлы стилей. Не уверен, что это сработает без SCSS, но внедрить SCSS очень легко:

1. Установить `npm i -D sass`;
2. Переименовать все расширения стилей в `.scss`.

2024-11-07 07:58 UTC, nelkor commented on reactChat/src/App.jsx
> +        {/* Передача searchTerm */}
Не уверен, что в этом комментарии есть смысл.

2024-11-07 07:58 UTC, nelkor commented on reactChat/src/components/ChatWindow.jsx
> +      const storedChats = JSON.parse(localStorage.getItem('chats'));
`JSON.parse(undefined)` — это красная ошибка в консоли.

2024-11-11 11:21 UTC, nelkor approved these changes
На будущее, для `JSON.parse` лучше использовать try/catch, так как мало ли что может оказаться в localStorage по разным причинам) Но на текущий момент всё хорошо.

2024-11-15 09:55 UTC, merged

2024-11-15 09:55 UTC, martinkomitsky commented
10