ДЗ 7
NikitaA-12/2024-2-VK-EDU-Frontend-N-Abramov pull request #15
Opened 2024-12-18 20:58 UTC by NikitaA-12

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его. 
https://nikitaa-12.github.io/2024-2-VK-EDU-Frontend-N-Abramov/#/

Что было сделано:

1. Использование задеплоенного backend
 * Обновили базовый URL для запросов axios: 
 * Теперь все запросы отправляются на адрес: https://vkedu-fullstack-div2.ru. 
 * Это гарантирует взаимодействие с задеплоированным backend вместо локального сервера. 
 
2. Интеграция API для чатов
Реализовали запросы для работы с чатом:
* Получение текущего пользователя: запрос /api/user/current/.
* Получение сообщений: запрос /api/messages/.
* Отправка сообщений: запрос /api/messages/ для публикации нового сообщения.
* Сообщения сохраняются в локальное хранилище и обновляются в интерфейсе после отправки и получения. 

3. Регистрация и авторизация
* Реализован метод для получения токена из локального хранилища (getToken).
* Отдельный экран для авторизации и регистрации 
* Токен используется для всех запросов к backend и хранится в localStorage. 

4. Получение сообщений в режиме реального времени
* Реализован метод для polling:
* Каждое обновление чата выполняется при смене currentChatId.
* Интерфейс обновляется после получения новых сообщений с сервера.
* Сообщения упорядочиваются по времени создания. 

5. Интеграция всех API в интерфейс
* Все API интегрированы в существующий интерфейс:
* Сообщения отображаются в порядке их создания.
* Аватары, имена отправителей и временные метки интегрированы в интерфейс.
* Сообщения отправляются и обновляются в локальном хранилище и интерфейсе.

2024-12-19 13:00 UTC, nelkor requested changes
Приложение не открывается по ссылке из описания.

2024-12-19 13:29 UTC, nelkor requested changes
Требуется возможность регистрации, иначе новый пользователь не зайдёт дальше первого экрана.

Создание чата немного непонятно. Я просто написал имя чата и всё, он создался. То есть это чат из одного человека.

2024-12-19 13:29 UTC, nelkor commented on reactChat/src/components/ChatContext.jsx
> +      const response = await $api.post(
Отправка POST-запроса с указанием пути, данных и заголовков — это слишком низкоуровневая логика для компонента. Будет лучше реализовать эту логику в отдельном модуле, отвечающим за работу с сетью.

2024-12-26 18:50 UTC, nelkor requested changes

2024-12-26 18:50 UTC, nelkor commented on reactChat/src/components/ChatWindow.jsx
> +      const response = await axios.post('/api/messages/', newMessage, {
В компонентах не должно быть HTTP-логики вообще. Она должна быть в отдельном модуле `api`. То есть если в компоненте есть полный путь запроса, FormData или слово "header", то это повод задуматься, как вынести это в `api`.

2025-01-03 07:14 UTC, nelkor approved these changes

2025-01-03 07:51 UTC, merged

2025-01-03 07:51 UTC, martinkomitsky commented
7